mode: rule
log-level: warning

ipv6: true

find-process-mode: always

tcp-concurrent: true

external-controller: localhost:9090
external-ui: ui
external-ui-url: "https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip"

profile:
  store-selected: true

tun:
  enable: true
  stack: mixed
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
    - tcp://any:53

dns:
  enable: true
  ipv6: true
  cache-algorithm: arc
  listen: :53
  enhanced-mode: redir-host

proxies:
  - name: ⚡ 直连
    type: direct
    udp: true

proxy-providers:
  Local:
    type: file
    path: proxies/local.yaml
    health-check:
      enable: true
      url: https://cp.cloudflare.com/generate_204
      interval: 86400

proxies-anchor:
  all-proxies: &all-proxies
    type: select
    include-all-providers: true

  all-proxies-auto-select: &all-proxies-auto-select
    type: url-test
    include-all-providers: true

  all-proxies-fallback: &all-proxies-fallback
    type: fallback
    include-all-providers: true

  default-proxies: &default-proxies
    type: select
    include-all-providers: true
    proxies: [默认, 美国, 台湾, 香港, 狮城, 日本]

proxy-groups:
  # 默认
  - name: 默认
    icon: https://raw.githubusercontent.com/ewigl/licons/refs/heads/main/logos/default.png
    type: select
    proxies: [自动选择, 美国, 台湾, 香港, 狮城, 日本, ⚡ 直连]

  # 自动选择
  - name: 自动选择
    icon: https://raw.githubusercontent.com/ewigl/licons/refs/heads/main/logos/auto.png
    <<: *all-proxies-auto-select

  # 区域
  - name: 美国
    icon: https://raw.githubusercontent.com/ewigl/licons/refs/heads/main/flags/us.png
    <<: *all-proxies-fallback
    filter: "US|🇺🇸|美国|United States"

  - name: 台湾
    icon: https://raw.githubusercontent.com/ewigl/licons/refs/heads/main/flags/cn.png
    <<: *all-proxies-fallback
    filter: "TW|🇨🇳|🇹🇼|台湾|Taiwan"

  - name: 香港
    icon: http://raw.githubusercontent.com/ewigl/licons/refs/heads/main/flags/hk.png
    <<: *all-proxies-fallback
    filter: "HK|🇭🇰|香港|HongKong|Hong Kong"

  - name: 狮城
    icon: https://raw.githubusercontent.com/ewigl/licons/refs/heads/main/flags/sg.png
    <<: *all-proxies-fallback
    filter: "SG|🇸🇬|新加坡|狮城|Singapore"

  - name: 日本
    icon: https://raw.githubusercontent.com/ewigl/licons/refs/heads/main/flags/jp.png
    <<: *all-proxies-fallback
    filter: "JP|🇯🇵|日本|Japan"

  # 服务
  - name: Bahamut
    icon: https://raw.githubusercontent.com/ewigl/licons/refs/heads/main/logos/bahamut.png
    <<: *all-proxies
    proxies: [台湾, 默认, 美国, 香港, 狮城, 日本]

  - name: GitHub
    icon: https://raw.githubusercontent.com/ewigl/licons/refs/heads/main/logos/github.png
    <<: *all-proxies
    proxies: [Microsoft, 默认, 美国, 台湾, 香港, 狮城, 日本]

  - name: Google
    icon: https://raw.githubusercontent.com/ewigl/licons/refs/heads/main/logos/google.png
    <<: *default-proxies

  - name: Imgur
    icon: https://raw.githubusercontent.com/ewigl/licons/refs/heads/main/logos/imgur.png
    <<: *default-proxies

  - name: Microsoft
    icon: https://raw.githubusercontent.com/ewigl/licons/refs/heads/main/logos/microsoft.png
    <<: *default-proxies

  - name: SteamCN
    icon: https://raw.githubusercontent.com/ewigl/licons/refs/heads/main/logos/steam.png
    <<: *all-proxies
    proxies: [⚡ 直连, 默认, 美国, 台湾, 香港, 狮城, 日本]

  - name: SteamGlobal
    icon: https://raw.githubusercontent.com/ewigl/licons/refs/heads/main/logos/steam.png
    <<: *default-proxies

  # 自定义
  - name: Elden Ring
    icon: https://raw.githubusercontent.com/ewigl/licons/refs/heads/main/logos/eldenring.png
    <<: *all-proxies
    proxies: [香港, 默认, 美国, 台湾, 狮城, 日本, ⚡ 直连]

  - name: FH4
    icon: https://raw.githubusercontent.com/ewigl/licons/refs/heads/main/logos/fh4.png
    <<: *all-proxies
    proxies: [香港, 默认, 美国, 台湾, 狮城, 日本, ⚡ 直连]

  - name: NRftW
    icon: https://raw.githubusercontent.com/ewigl/licons/refs/heads/main/logos/nrftw.png
    <<: *all-proxies
    proxies: [香港, 默认, 美国, 台湾, 狮城, 日本, ⚡ 直连]

  # 其他
  - name: 其他
    icon: https://raw.githubusercontent.com/ewigl/licons/refs/heads/main/logos/misc.png
    <<: *default-proxies

  # 全局
  - name: GLOBAL
    icon: https://raw.githubusercontent.com/ewigl/licons/refs/heads/main/logos/global.png
    type: select
    include-all-providers: true
    proxies: [默认, 自动选择, 美国, 台湾, 香港, 狮城, 日本, ⚡ 直连]

rule-anchor:
  domain: &domain { type: http, interval: 86400, behavior: domain, format: mrs }
  cidr: &cidr { type: http, interval: 86400, behavior: ipcidr, format: mrs }

rule-providers:
  # Mihomo 规则集: https://github.com/MetaCubeX/meta-rules-dat/blob/meta/geo/geosite
  ## 域名规则集
  bahamut:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bahamut.mrs"

  cn:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"

  github:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs"

  google:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs"

  imgur:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/imgur.mrs"

  microsoft:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs"

  private:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"

  steam:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/steam.mrs"

  steam@cn:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/steam@cn.mrs"

  ## IP 规则集
  cncidr:
    <<: *cidr
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"

  privatecidr:
    <<: *cidr
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs"

rules:
  # 自定规则
  ## 直连
  - PROCESS-NAME,piliplus.exe,DIRECT
  - PROCESS-NAME,WeChatAppEx.exe,DIRECT
  - PROCESS-NAME,Weixin.exe,DIRECT
  ## 选择
  ### 艾尔登法环
  - PROCESS-NAME,eldenring.exe,Elden Ring
  ### 恶意不息
  - PROCESS-NAME,NoRestForTheWicked.exe,NRftW
  ### Forza Horizon 4
  - PROCESS-NAME,ForzaHorizon4.exe,FH4

  # 官方规则
  ## 直连
  - RULE-SET,private,DIRECT
  - RULE-SET,privatecidr,DIRECT,no-resolve
  - RULE-SET,cn,DIRECT
  - RULE-SET,cncidr,DIRECT,no-resolve
  ## 选择
  ### Google
  - RULE-SET,google,Google
  ### Microsoft
  - RULE-SET,github,GitHub
  - RULE-SET,microsoft,Microsoft
  ### Steam
  - RULE-SET,steam@cn,SteamCN
  - RULE-SET,steam,SteamGlobal
  ### 其他
  - RULE-SET,bahamut,Bahamut
  - RULE-SET,imgur,Imgur

  # 其他
  - MATCH,其他
